### ISSUE TITLE
not enough arr

### ISSUE THREAD

**Issue by SuperCoder7979** [fabric-community/Everything-API#17]
hey guys, this is a great project! i really hope to contribute in the future. unfortunately, i don't see a lot of arr in here. I like to be in control of all my projects and i think you should be to. that's why i suggest moving this project to arr. you can give individual people rights while also keeping your own! it's a win-win situation.

**Comment by Devan-Kerman** [comment]
i trid but my pr as cloased
https://github.com/fabric-community/Everything-API/pull/4

**Comment by toolsharpest** [comment]
I'd just like to interject for a moment. What you're referring to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called "Linux", and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called "Linux" distributions are really distributions of GNU/Linux.

**Comment by MAX1234567890** [comment]
Android's open nature, unlike other mobile systems, made it an attractive platform for hobbyist development, which has led to third-party forks namely AOKP, Cyanogenmod and Replicant, a fully-libre Android distribution aiming to replace all non-free Android components and drivers with open-source equivalents. Rooting, a process that allows for full system access on one's device is also a popular practice among hackers[4]; numerous safeguards implemented on certain phones and tablets, notably on popular Samsung and HTC models, prevent this, but workarounds exist to defeat such restrictions.

On a typical user's standpoint, this means more freedom compared to iOS, as installing applications, themes and media from third-party sources other than those provided by the device, e.g. Google Play or SlideME, is of trivial matter, but this has also led to bigger piracy rates owing to lax security measures.

**Comment by valoeghese** [comment]
there's the actual content, and then there's the :hankey: posting
