### ISSUE TITLE
🚨 RULE BROKEN!

### ISSUE THREAD

**Issue by ramidzkh** [fabric-community/Everything-API#36]
The [Apache Groovy](https://groovy-lang.org/) [Gradle](https://gradle.org/) [buildscripts](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html) are breaking the [second rule](https://github.com/fabric-community/Everything-API/blob/master/README.md#contributing)

I propose we use the [Jeka build system](https://jeka.dev/)

**Comment by Boundarybreaker** [comment]
https://www.youtube.com/watch?v=u8FHwPl7bH4

**Comment by ramidzkh** [comment]
This is not a laughing matter!

**Comment by hYdos** [comment]
i agree this needs serious attention

**Comment by Devan-Kerman** [comment]
yes
